CREATE TABLE `carpool` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) unsigned NOT NULL,
  `src_latitude` double(11,8) DEFAULT NULL,
  `src_longitude` double(11,8) DEFAULT '0.00000000',
  `dst_latitude` double(11,8) DEFAULT NULL,
  `dst_longitude` double(11,8) DEFAULT '0.00000000',
  `created` datetime DEFAULT NULL,
  `lastupd` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `src_locality` varchar(255) DEFAULT NULL,
  `src_address` varchar(255) DEFAULT NULL,
  `dst_locality` varchar(255) DEFAULT NULL,
  `dst_address` varchar(255) DEFAULT NULL,
  `type` tinyint(4) DEFAULT '0',
  `route_id` int(10) unsigned DEFAULT NULL,
  `city` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `user_id` (`user_id`),
  KEY `user_id_2` (`user_id`),
  KEY `src_lattitude` (`src_latitude`,`src_longitude`,`dst_latitude`,`dst_longitude`)
) ENGINE=InnoDB AUTO_INCREMENT=73 DEFAULT CHARSET=latin1
